version: '3.8'

services:
  mysql-serviceJava:
    image: mysql:8.0
    container_name: mysql_container_Java
    environment:
      MYSQL_DATABASE: bd_service
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: